"""Command handlers for scaffold CLI."""

from src.qual.commands.catalog import (
    CommandSpec,
    CommandFlowEntry,
    CommandManifestEntry,
    canonical_command,
    command_aliases,
    command_flow_steps,
    command_flow_manifest,
    command_lookup_table,
    command_lookup_tokens,
    command_manifest,
    command_mvp_flow,
    command_mvp_flow_names,
    command_mvp_flow_catalog,
    command_mvp_flow_lookup_table,
    command_mvp_flow_steps,
    command_names,
    command_spec,
    command_specs,
    command_tokens,
    validate_command_catalog,
)

__all__ = [
    "CommandSpec",
    "CommandFlowEntry",
    "CommandManifestEntry",
    "canonical_command",
    "command_aliases",
    "command_flow_steps",
    "command_flow_manifest",
    "command_lookup_table",
    "command_lookup_tokens",
    "command_manifest",
    "command_mvp_flow",
    "command_mvp_flow_names",
    "command_mvp_flow_catalog",
    "command_mvp_flow_lookup_table",
    "command_mvp_flow_steps",
    "command_names",
    "command_spec",
    "command_specs",
    "command_tokens",
    "validate_command_catalog",
]
