"""Command handlers for scaffold CLI."""

from src.qual.commands.catalog import (
    CommandCatalogEntry,
    CommandSpec,
    canonical_command,
    command_catalog_entries,
    command_catalog_entries_for_role,
    command_catalog_index,
    command_catalog_entry,
    command_aliases,
    command_lookup_names,
    command_lookup_index,
    command_mvp_flow_names,
    command_mvp_flow_entries,
    command_mvp_flow_index,
    command_mvp_flow_lookup_names,
    command_mvp_flow_specs,
    command_mvp_role,
    command_mvp_roles,
    command_names,
    command_names_for_role,
    command_lookup_names_for_role,
    command_spec,
    command_specs,
    command_specs_for_role,
)

__all__ = [
    "CommandCatalogEntry",
    "CommandSpec",
    "canonical_command",
    "command_catalog_entries",
    "command_catalog_entries_for_role",
    "command_catalog_index",
    "command_catalog_entry",
    "command_aliases",
    "command_lookup_names",
    "command_lookup_index",
    "command_mvp_flow_names",
    "command_mvp_flow_entries",
    "command_mvp_flow_index",
    "command_mvp_flow_lookup_names",
    "command_mvp_flow_specs",
    "command_mvp_role",
    "command_mvp_roles",
    "command_names",
    "command_names_for_role",
    "command_lookup_names_for_role",
    "command_spec",
    "command_specs",
    "command_specs_for_role",
]
