"""Public UI surface for A2UI rendering and CLI fallback helpers."""

from .a2ui import (
    A2UI_CONTRACT_VERSION,
    A2UI_VERSION,
    A2UICapabilities,
    A2UISessionStore,
    ActionRef,
    DEFAULT_UNKNOWN_CARD_PREVIEW_BYTES,
    FALLBACK_COPY_ACTION_ID,
    GENERIC_CARD_TYPE,
    GENERIC_FALLBACK_SUBTITLE,
    UNKNOWN_CARD_TYPE,
    UNKNOWN_FALLBACK_SUBTITLE,
    a2ui_contract_fingerprint,
    build_unknown_card,
    describe_a2ui_contract,
    engine_prepare_card,
    execute_action_with_policy_gate,
    normalize_action_ref,
    render_terminal_card,
    studio_materialize_card,
    validate_action_ref,
    validate_capabilities,
    validate_generic_card,
    validate_primitive_block,
    validate_unknown_card,
)
from .shell import ShellUI

__all__ = [
    "A2UI_CONTRACT_VERSION",
    "A2UI_VERSION",
    "A2UICapabilities",
    "A2UISessionStore",
    "ActionRef",
    "DEFAULT_UNKNOWN_CARD_PREVIEW_BYTES",
    "FALLBACK_COPY_ACTION_ID",
    "GENERIC_CARD_TYPE",
    "GENERIC_FALLBACK_SUBTITLE",
    "ShellUI",
    "UNKNOWN_CARD_TYPE",
    "UNKNOWN_FALLBACK_SUBTITLE",
    "a2ui_contract_fingerprint",
    "build_unknown_card",
    "describe_a2ui_contract",
    "engine_prepare_card",
    "execute_action_with_policy_gate",
    "normalize_action_ref",
    "render_terminal_card",
    "studio_materialize_card",
    "validate_action_ref",
    "validate_capabilities",
    "validate_generic_card",
    "validate_primitive_block",
    "validate_unknown_card",
]
